### ISSUE TITLE
Fix errors for ATTiny

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8glib#190]
Originally reported on Google Code with ID 190

```
Arduino-1.0.5-u8glib include ATTiny boards --> fix errors reported there

```

Reported by `olikraus` on 2013-07-13 05:57:30

**Comment by aliafshar** [comment]
I can't fit u8glib on an attiny85. Anything I am doing wrong? I use an r postfixed font:

{{{
/home/afshar/tmp/arduino-1.6.5/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/bin/ld: sh1106_test_tiny.cpp.elf section `.text' will not fit in region `text'
/home/afshar/tmp/arduino-1.6.5/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/bin/ld: region `text' overflowed by 794 bytes
collect2: error: ld returned 1 exit status
Error compiling.
}}}

**Comment by olikraus** [comment]
I personally have never tested any ATtiny. But u8glib will probably never fit into 4K flash.

**Comment by aliafshar** [comment]
Ok, thanks.
