### ISSUE TITLE
Custom offset

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8glib#312]
Originally reported on Google Code with ID 313
```
Some low cost SSD1306 128x64 displays, especially the 1.3" I2C only versions, suffer
from an offset of 2 pixel columns, shown as garbage. This can be fixed by changing
the library u8g_dev_ssd1306_128x64.c.

static const uint8_t u8g_dev_ssd1306_128x64_data_start[] PROGMEM = {
  U8G_ESC_ADR(0),           /* instruction mode */
  U8G_ESC_CS(1),             /* enable chip */
  0x010,		/* set upper 4 bit of the col adr to 0 */
  0x000,		/* set lower 4 bit of the col adr to 0  */
  U8G_ESC_END                /* end of sequence */
};

The value 0x000 needs to be changed to the number of wrong columns shown (a value of
0x002 fixed my problem).

It would be nice to make this value programmable so a user can change the default value
without altering the library.



What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Reported by `sleurhutje` on 2015-01-27 15:10:03

**Comment by jpoppe** [comment]
I have bought the following display: http://www.aliexpress.com/item/1-3inch-white-color-light-with-Factory-direct-selling-price/32621381539.html

I also have the 'offset issue' with this display, the OP mentioned fix also works for me (changing 0x000 to 0x002). I have tried SH1106 as a device but that does not work. I would prefer to use U8g2 but the code seems pretty different and I don't know where to modify this value in: clib/u8x8_d_ssd1306_128x64_noname.c

**Comment by jpoppe** [comment]
Removed my comment since I have got it working working with: U8G2_SH1106_128X64_NONAME_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 13, /* data=*/ 11, /* cs=*/ 10, /* dc=*/ 9, /* reset=*/ 8);

Sorry for the noise, and thanks for your awesome library!

**Comment by olikraus** [comment]
Ok, great
