### ISSUE TITLE
U8lib 1.18.0 will not compile on Arduino with SAMD (Cortex M0+) devices.

### ISSUE THREAD

**Issue by TGosselink** [olikraus/u8glib#353]
I found a problem trying to compile for the Autonomo or Zero boards (SAMD, Cortex M0+) devices.
Arduino version 1.6.5

Problem is in: \Arduino\libraries\U8glib\src\clib\u8g_delay.c

 adding:
`#if defined(ARDUINO_ARCH_SAMD)`
`#    include <delay.h>`
`#endif`
After line 53 (edited)

This solves the problem.
Will you please update the code for a newer release?
Thanks a ton.

**Comment by olikraus** [comment]
Thanks for reporting.

**Comment by olikraus** [comment]
added the code, but probably needs to be tested
