### ISSUE TITLE
Random pixel on 128x32 SainSmart Display

### ISSUE THREAD

**Issue by jstrobel** [olikraus/u8glib#354]
Hi,
i've connected a SainSmart 0.91" 128x32 Display to an Arduino Pro mini. I use the i2c Pins A4 / A5 and VCC and GND. When i upload some example source with:
U8GLIB_SSD1306_128X32 u8g(U8G_I2C_OPT_NO_ACK);

I got the result as seen on the attached image. When i am using the adafruit-Library i got some normal output. What i am doing wrong?

Thanks
Jens
![img_5202](https://cloud.githubusercontent.com/assets/1428396/8894518/a775d71e-33b9-11e5-8258-ede5e07e11e6.JPG)

**Comment by olikraus** [comment]
What happens with the GraphicsText example? Do you see some pixels moving around?

**Comment by jstrobel** [comment]
After using the GraphicsText-Example and readding my source everything works now.
Sorry, can't reproduce why it hasn't worked before.
