### ISSUE TITLE
Fix font data

### ISSUE THREAD

**Issue by olikraus** [olikraus/u8glib#356]
u8g_font_data.c:18746:const u8g_fntpgm_uint8_t u8g_font_fub20t[477] U8G_SECTION(".progmem.u8g_font_fub20t") = {
--> shound not be U8G_SECTION

**Comment by jbhome** [comment]
So then what should it be

On Aug 1, 2015 10:48 AM, "olikraus" <notifications@github.com> wrote:
>
> u8g_font_data.c:18746:const u8g_fntpgm_uint8_t u8g_font_fub20t[477]
U8G_SECTION(".progmem.u8g_font_fub20t") = {
> --> shound not be U8G_SECTION
>
> —
> Reply to this email directly or view it on GitHub.

Jim

**Comment by olikraus** [comment]
The font should not be there at all.

**Comment by jbhome** [comment]
Off topic but....
What are the spi settings for st7920 spi ?

**Comment by olikraus** [comment]
which settings?

**Comment by jbhome** [comment]
All settings associated with spi configuration
I would like to use spi.transaction but having difficulty finding where and
what settings are used to initialize the device

**Comment by olikraus** [comment]
the SPI settings for the ST7920 are mentioned in the datasheet for the ST7920

**Comment by jbhome** [comment]
Sorry what are the arduino settings you use in u8g?

**Comment by olikraus** [comment]
you could study u8g_com_arduino_st7920_hw_spi.c

I have a remark in that file:

      /* 20 Dez 2012: set CPOL and CPHA to 1 !!! */
      SPCR =  (1<<SPE) | (1<<MSTR)|(0<<SPR1)|(0<<SPR0)|(1<<CPOL)|(1<<CPHA);

**Comment by jbhome** [comment]
Ok
So you don't use the arduino spi configuration functions
Sorry to be a pain
With the library supporting so many configuration finding the right place
is challenging specially when it's in c++ and I'm still learning
Thanks for your help AND your patience
Sincerely
Jim

**Comment by olikraus** [comment]
No problem. I hope to support Arduino standard SPI in the future.

**Comment by olikraus** [comment]
the original issue is fixed
