### ISSUE TITLE
Set contrast for SH1106

### ISSUE THREAD

**Issue by 7134956** [olikraus/u8glib#376]
case U8G_DEV_MSG_CONTRAST:
			{
				u8g_SetChipSelect(u8g, dev, 1);
				u8g_SetAddress(u8g, dev, 0); /* instruction mode */
				u8g_WriteByte(u8g, dev, 0x81);
				u8g_WriteByte(u8g, dev, *(uint8_t *) arg);
				u8g_SetChipSelect(u8g, dev, 0);
			}break;

**Comment by olikraus** [comment]
Thanks, added to the code
