### ISSUE TITLE
Unused parameter compiler warnings

### ISSUE THREAD

**Issue by steronydh** [olikraus/u8glib#402]
Just a minor thing, I'm getting these with the Arduino IDE:

...\Arduino\libraries\U8glib\src\clib\u8g_dev_null.c: In function 'u8g_dev_null':

...\Arduino\libraries\U8glib\src\clib\u8g_dev_null.c:39:29: warning: unused parameter 'u8g' [-Wunused-parameter]

 uint8_t u8g_dev_null(u8g_t *u8g, u8g_dev_t *dev, uint8_t msg, void *arg)

                             ^

...\Arduino\libraries\U8glib\src\clib\u8g_dev_null.c:39:45: warning: unused parameter 'dev' [-Wunused-parameter]

 uint8_t u8g_dev_null(u8g_t *u8g, u8g_dev_t *dev, uint8_t msg, void *arg)

                                             ^

...\Arduino\libraries\U8glib\src\clib\u8g_dev_null.c:39:69: warning: unused parameter 'arg' [-Wunused-parameter]

 uint8_t u8g_dev_null(u8g_t *u8g, u8g_dev_t *dev, uint8_t msg, void *arg)

**Comment by olikraus** [comment]
well, thats the purpose of the null device.
Guess this will be solved with u8g2
