### ISSUE TITLE
Ampire AG240128G we are approching ;)

### ISSUE THREAD

**Issue by sigmounte** [olikraus/u8glib#410]
Hello , 

here is my display: 
http://www.chunfung.com.cn/en/productview.asp?id=300

and the result using your librarie: 
http://pasteboard.co/GfIL7iR.jpg
![20160504_002](https://cloud.githubusercontent.com/assets/16653670/15031125/e8053e06-1256-11e6-9f06-768a37950321.jpg)ks !

Do you have any idea what value i should change ?

Thanks !

**Comment by olikraus** [comment]
connect pin 19 (FS) to GND

Oliver

**Comment by sigmounte** [comment]
Thanks you so much !

(  adding the pdf with the pinout specific to this model of ampire for other people who need it ) 

[P037-AG240128I.pdf](https://github.com/olikraus/u8glib/files/251090/P037-AG240128I.pdf)
