### ISSUE TITLE
Add horizontal flip

### ISSUE THREAD

**Issue by gcstr** [olikraus/u8glib#426]
We are working on a project where we need to flip the entire screen.
When working with shapes and primitives, it's ok, since it's just a matter of math.

But texts are not ok.
It would be nice if the lib could support something like `setHFlip` and the screen flipped horizontally, something like `setRot90`, `setRot180`... but flipping the entire screen.

**Comment by olikraus** [comment]
You mean, the text should appear mirrored? So to say, readable only with a mirror?

**Comment by goocastro** [comment]
Exactly.
Some wearables, like the one we are prototyping, might require that.

I managed to achieve the result I wanted playing with adafruit's library. 
C isn't really my main language, so the code I wrote is really simple, but did the trick for now:

```
void Adafruit_SSD1306::flip(void){
  for (int i=0; i<8; i++) {
    reverse(buffer, SSD1306_LCDWIDTH*i, SSD1306_LCDWIDTH*i+(SSD1306_LCDWIDTH-1));
  }
}
```
I simply iterate through the buffer reversing the array.

**Comment by goocastro** [comment]
Actually, I got the starting idea from here:

http://nerdclub-uk.blogspot.com.br/2016/03/adding-flip-function-to-adafruits.html?m=1

But it only rotates the screen, feature already in u8g.

I`d like to contribute to the repo, but as I said, it's not my main language. It's just a feature request. 😀

**Comment by olikraus** [comment]
you could try to change the value 0x0c8 to 0x0c0 in line 130 of u8g_dev_ssd1306_128x64.c (assumming you have this display)

**Comment by goocastro** [comment]
Yap, that's my display.
I'll try that tonight.

**Comment by olikraus** [comment]
any success?

**Comment by goocastro** [comment]
Perfect!
It worked. Thank you very much.

**Comment by johnny-82** [comment]
Hi olikraus!
sorry for my English.
I need to flip horizontally my old "nokia 5210 lcd". I am using U8GLIB_PCD8544.
Can you help me change the code? do I have to edit the file "u8g_dev_pcd8544_84x48.c"?

**Comment by olikraus** [comment]
what about using setRot180?

**Comment by olikraus** [comment]
ok, I see. What about using u8g2 (which is u8glib version 2). It includes a mirror option should solve the problem.

**Comment by johnny-82** [comment]
thanks a lot! It work with "U8G2_PCD8544_84X48_F_4W_SW_SPI u8g2(U8G2_MIRROR, /* clock=..."

**Comment by olikraus** [comment]
HW SPI might be better

**Comment by SteveC00k** [comment]
I have a similar issue. The text is mirrored.
I used this display setting: 

> u8g_dev_sbn1661_122x32.c

I altered the lines 54 and 59 to 0x0a and it did not mirror. See gfx below.

Here is what it looks like with the settings before altering.
![img_9709](https://user-images.githubusercontent.com/995817/48966896-9be98600-ef8d-11e8-90d1-d835d742b92f.JPG)

Here is what it looks like after altering.
![img_9710](https://user-images.githubusercontent.com/995817/48966899-a146d080-ef8d-11e8-9338-9c552f2cf38f.JPG)

Back of LCD.
![img_9711](https://user-images.githubusercontent.com/995817/48966903-a9067500-ef8d-11e8-9846-7e154cad5238.JPG)

![screenshot_10](https://user-images.githubusercontent.com/995817/48966878-68a6f700-ef8d-11e8-97ea-4575ba1f674c.png)

**Comment by SteveC00k** [comment]
Here is the datasheet if anyone needs to see it. https://drive.google.com/open?id=1gbZHPdsXN4bUGbe_5cXVszRSPaIAwO8v

**Comment by SteveC00k** [comment]
Started to use the ug82 lib.
I managed to get it working except half the text is chopped off on one of the examples.

**Comment by SteveC00k** [comment]
I have it working now. Found out how to get it going using this profile in the examples.
U8G2_SED1520_122X32_1 u8g2(U8G2_MIRROR, 8, 9, 10, 11, 4, 5, 6, 7, /*dc=*/ A0, /*e1=*/ A3, /*e2=*/ A2, /* reset=*/  U8X8_PIN_NONE);   // Set R/W to low!

**Comment by gdattn** [comment]
I had such a problem with flipped screen while trying to connect 3d printer mainboard MKS-Robin-E3D to COG screen ST7567 with Marlin firmware. Problem solved thanks to this thread. Changes in \Marlin\src\lcd\dogm\u8g_dev_uc1701_mini12864_HAL.cpp in line 71:
change
#define UC1701_OUT_MODE(N)       ((N) ? 0xC8 : 0xC0)
to
#define UC1701_OUT_MODE(N)       ((N) ? 0xC0 : 0xC8)
