### ISSUE TITLE
Issue on Teensy + U8Glib with SleepOn/Off on SSD1322

### ISSUE THREAD

**Issue by christophepersoz** [olikraus/u8glib#429]
Hello,

I'm currently running U8Glib on a SSD1322 display on Teensy 3.2 board. Everything is working great, without any issues except if I'm using SleepOn() and SleepOff() functions which creates strange behaviors.

Here the simple code that makes the both functions works (just mentioned the parts that worth it, not the Chris O wrapper for Teensy etc. which is working well) :

``` c++
void testSleep()
{
  (i) ? _U8G.sleepOn( ) : _U8G.sleepOff();
  (i) ? Serial.println("on") : Serial.println("off");
  i = !i;
}

void loop() {
  _U8G.firstPage();
  do {
    testSleep();
    delay(2000);
  } while( _U8G.nextPage() );
}
```

And here the code that makes them not working and turn the screen off :

``` c++
void testSleep()
{
  (i) ? _U8G.sleepOn() : _U8G.sleepOff();
  i = !i;
}

void loop() {
  _U8G.firstPage();
  do {
    testSleep();
    delay(2000);
  } while( _U8G.nextPage() );
}
```

The only difference is the Serial output which makes the use of sleep function working well. As soon as I'm removing them, any call to sleepOn() or sleepOff() turn off the screen.

I had a look on the SSD1322 reference and the address for those functionality are correct.
I thought about a timing issues, but introduce delay() doesn't change anything.

Any idea ?

Thanks

**Comment by odenizot** [comment]
Hello Christophe,

I think the static declaration of variable i is missing in function testSleep.

Cordially.

Olivier.

**Comment by olikraus** [comment]
If i is not zero initially, the sleepOn will be called.
So: diffucult to say without the rest of the code

**Comment by christophepersoz** [comment]
Hello Oliver, it seems ok now, sleepOn() and sleepOff() is working correctly, my mistake.
