### ISSUE TITLE
arduino --install-library "U8glib" failed

### ISSUE THREAD

**Issue by thinkyhead** [olikraus/u8glib#430]
I'm seeing this in Travis-CI when we try to use the Arduino built-in install method. For some reason the command is failing, citing a bad CRC.
```
Verifying archive integrity...
java.lang.Exception: CRC doesn't match. File is corrupted.
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:77)
	at cc.arduino.contributions.libraries.LibraryInstaller.install(LibraryInstaller.java:97)
	at processing.app.Base.<init>(Base.java:415)
	at processing.app.Base.guardedMain(Base.java:223)
	at processing.app.Base.main(Base.java:136)
The command "arduino --install-library "U8glib"" failed and exited with 255 during .
```
Is it possible the version of u8glib stored at arduino.cc has been corrupted?

**Comment by thinkyhead** [comment]
I've notified Arduino also. arduino/Arduino#3206

**Comment by olikraus** [comment]
I am not working much on u8glib (instead there is version 2, u8g2). But maybe i should create another release to ensure, that the library is valid.

**Comment by thinkyhead** [comment]
I altered our `.travis.yml` to download directly from Github and it works well. Might even be faster, who knows?

**Comment by facchinm** [comment]
Should be solved now by rebuilding the whole library index. Thanks for reporting!
