### ISSUE TITLE
Fail to modify the initialization parameters-U8GLIB_NHD_C12864

### ISSUE THREAD

**Issue by yifanshu02** [olikraus/u8glib#431]
hi，olikraus and ALL：
Now i have a LCD which ic is ST7565,but it is 132*64 and Contrast、the location of (1,1) ect. is different with NHD_C12864.
So i want to modify the initialization parameters and WIDTH .
Then i modify some initialization parameters and WIDTH to 132 in "u8g_dev_st7565_nhd_c12864.C".
After modify , it do not work
Please help me

**Comment by yifanshu02** [comment]
i have solved it.
two to install U8GLIB...always modify the invalid one......
:D

**Comment by olikraus** [comment]
:+1:
