### ISSUE TITLE
Error trying out "Hello World" example.

### ISSUE THREAD

**Issue by alidaf** [olikraus/u8glib#434]
'u8g' was not declared in this scope.

I can't find any info on this other than an obscure reference on the Arduino forum to remove a comment from the constructor but I can't find where the constructors are.

**Comment by alidaf** [comment]
I've figured it out. I have been trying to follow the tutorial page, https://github.com/olikraus/u8glib/wiki/thelloworld, which is missing the 'u8g' after the constructor name but before the parameters. I didn't realise that there was a tutorial already coded up. I had a look at that but had to change a few things to get it to work.

**Comment by olikraus** [comment]
thanks, i fixed the tutorial
