### ISSUE TITLE
Fixed support for KS0108 display controllers with three chip select lines (CS1,CS2,CS3).

### ISSUE THREAD

**Issue by RndMnkIII** [olikraus/u8glib#438]
Fixed support for KS0108 display controllers with three chip select lines (CS1,CS2,CS3). Tested with the 
[buydisplay.com KS0108 192x64 screen](http://www.buydisplay.com/default/4-inch-192x64-graphic-lcd-module-display-w-ks0107-ks0108-white-on-black).

![20161016_140547](https://cloud.githubusercontent.com/assets/5108152/19417920/29b2c2a4-93b9-11e6-90e0-c88e69ca071f.jpg)

Fixed issue number: #432

Source code modifications in:
[https://github.com/RndMnkIII/U8glib/commits/master](https://github.com/RndMnkIII/U8glib/commits/master)

**Comment by olikraus** [comment]
nice work

**Comment by RndMnkIII** [comment]
can add support fot this display controller in u8g2?
