### ISSUE TITLE
Grayshade bitmap for drawBitmap

### ISSUE THREAD

**Issue by christophepersoz** [olikraus/u8glib#444]
Hi Oliver,

Actually drawBitmap() draws in black and white (0/1) values. Do you think it can be possible to draw bitmap in gray shade on displays that support more color values ?

Thanks

**Comment by olikraus** [comment]
I have almost stopped development for u8glib and I will concentrate on u8g2.
The only drawback is, I have stopped graylevel support completly to simplify the software architecture. So... i do not support this any more in u8glib and i will not support graylevel in u8g2 (although some minimal graylevel support might be thinkable).

**Comment by christophepersoz** [comment]
Too bad, I can understand that means heavier code. I will have a look on your code if there is a way to display a bitmap in grayscale or not.
In my proper opinion, grayscale increase readability, and allow to focus on some parts of the display. So for my current app I will stay on U8Glib thought ;)

Thanks for your quick reply!

**Comment by olikraus** [comment]
You are the first person ever who had asked for graylevel support. I had assumed, that this is of almost no use. For my own projects I also never needed graylevel support.

**Comment by christophepersoz** [comment]
Funny. No prob ;)
