### ISSUE TITLE
bdf2u8g "Glyph with encoding 37 is too large (315 > 255)"

### ISSUE THREAD

**Issue by anubisis** [olikraus/u8glib#445]
Hi!

I am trying to convert 60 px freeuniversal font in height to u8glib format using bdf2u8g. But there seems to be some limitations. Please, it is possible to fix this?
I need such a huge custom font for my display (additionally, I may try printSizedString implemented by Flo1991)

Thank you!

**Comment by olikraus** [comment]
You have to use u8g2. This is one of the issues, which got resolved (at least the limit got extended) with the second version of u8glib, which is now called u8g2.

https://github.com/olikraus/u8g2

Note that bdf2u8g has been renamed to bdfconv and it is located here:
https://github.com/olikraus/u8g2/tree/master/tools/font/bdfconv

here is free universal from u8g2:
https://github.com/olikraus/u8g2/wiki/fntgrpfreeuniversal#fur49

one more point: Some limitation is still there. Especially it might be possible that the glyph "@" will violate this limitation for 60px height. In this case it is possible now with bdfconv to remove one or more chars: See the -m option for this. Please raise an issue in u8g2 if you have more questions.
