### ISSUE TITLE
right align text

### ISSUE THREAD

**Issue by waspinator** [olikraus/u8glib#467]
How would I alight text to the right? For example if I had the numbers, "1", "12", and "123", the default behavior is to display them from the left:

    1
    12
    123

Instead, I'd like to display them the other way around:

      1
     12
    123

**Comment by olikraus** [comment]
hmm, this is more a programming question, i guess.
You could use a monospaced font together with sprintf()
If i remember correctly
char buf[10];
sprintf(buf, "%3d", 1);
will put "<blank><blank>1" into the buffer, which could be drawn by the u8glib procedures

**Comment by waspinator** [comment]
okay, thanks I'll try that. I thought maybe the library had an option for aligning text.
