### ISSUE TITLE
NHD-2.7-12864WDY3 driver update

### ISSUE THREAD

**Issue by conectia** [olikraus/u8glib#476]
Hi,

The new NHD-2.7 128x64 oled display comes with the ssd1322 controller instead of the ssd1325.

I have been trying to replace it with your ssd1322 256x64 controller.

The display works, but I get scrambled output. The display shows one half with the output compressed and the other one with garbage.

I think it will be easy to make it work touching a few bits.

Any idea.

Thanks in advance.

**Comment by olikraus** [comment]
Can you link the datasheet and/or the product description?

**Comment by conectia** [comment]
The product page : http://www.newhavendisplay.com/nhd2712864wdy3-p-9542.html

And two images, the old working ssd1325 and the result shown with the ssd1322
![ssd1325](https://user-images.githubusercontent.com/34215725/33542766-ae7df18c-d8d4-11e7-83b4-46c6cdb2e0a5.JPG)
![ssd1322](https://user-images.githubusercontent.com/34215725/33542768-b2f0b02e-d8d4-11e7-8395-4a58ffa8395d.JPG)

Thanks

**Comment by conectia** [comment]
Partially solved !

Replacing the driver:

U8G2_SSD1325_NHD_128X64_1_4W_HW_SPI u8g2(U8G2_R0, /* cs=*/ A1, /* dc=*/ A0);
to
U8G2_SSD1322_NHD_256X64_1_4W_HW_SPI u8g2(U8G2_R2, /* cs=*/ A1, /* dc=*/ A0);

Setting   u8g2.setFlipMode(1); I get the horizontal mirror.

Updating   U8X8_CAA(0x0a0, 0x014, 0x011),                /* remap */
to   U8X8_CAA(0x0a0, 0x004, 0x011),                /* remap */

I get a vertical mirror.
But still the image is compressed horizontally.

Any idea ?

Thanks in advance.
![img_5235](https://user-images.githubusercontent.com/34215725/33780660-db607ece-dc51-11e7-940b-59058d7482f4.JPG)

**Comment by olikraus** [comment]
Is this the same display: https://github.com/olikraus/u8g2/issues/412 ?

Does this issue belong to u8g2?

**Comment by conectia** [comment]
Yes, I'll update issue 412
