### ISSUE TITLE
Multiple screens support

### ISSUE THREAD

**Issue by AbanoubMamdouh** [olikraus/u8glib#489]
Hello,
Thank you very much for your amazing work. I am working on a project where I want to use 2 ST7920 screens together. Up until now, I haven't found any way to do that. Is there a way to make them work together at the same time?

**Comment by olikraus** [comment]
Shouldn't be a problem. Did you had a look into FAQ?

**Comment by AbanoubMamdouh** [comment]
Thank you very much! Found it! In case someone needs it, here is the link: https://github.com/olikraus/u8g2/blob/master/doc/faq.txt#L226
