### ISSUE TITLE
u8g2 stops the Arduino Nano Every with I2C and DOGXL240

### ISSUE THREAD

**Issue by Algorab** [olikraus/u8glib#508]
Hello Olikraus,

after several seconds or some minutes the Arduino is stopping or maybe internally crashing.
Have an Arduino NANO Every with a DOG XL 240 Display connected with I2c. When I run
a little counter example for reproduce after a several seconds or minutes the Arduino is 
stop working. Then I have to reset then it is start again and stops again after a while.

This happens in frame also in the page mode. In the page mode the stops happen later
as in the frame mode what I could observe.

Arduino IDE: 1.8.12
Board: Arduino Nano Every
MCU: ATmega4809

avrdude: Version 6.3-20190619
Programmer : jtag2updi

I attached a sketch for reproduce.
[DisplayRun.ino.txt](https://github.com/olikraus/u8glib/files/4758554/DisplayRun.ino.txt)

**Comment by olikraus** [comment]
ok, yes, should be u8g2 repo :-)
