### ISSUE TITLE
I'm using KS0108 controller based GLCD

### ISSUE THREAD

**Issue by Eldho1416** [olikraus/u8glib#522]
I interface the GLCD with uno using this library and it worked perfectly fine and while exploring about the library i noticed that it can be installed in Raspberry Pi as well can someone help me how to install the library in RPi 
@olikraus

**Comment by olikraus** [comment]
I do not work on u8glib, instead u8g2 is the successer. However installation on Raspberry Pi is not supported although some users contributed solutions for u8g2.

**Comment by Eldho1416** [comment]
thank you for the reply, i went through u8g2 library i'm having trouble in displaying will raise an issue there
